<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>test all</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-11T00:23:57</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d33c1659-1da8-4373-bd6c-8a2c6b1a9063</testSuiteGuid>
   <testCaseLink>
      <guid>62087a9c-f348-48e4-a035-9697a428db4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test add product and carts display</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>810283a3-9582-449a-92de-c4e36d408173</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/add product and carts display</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b59a08b-9dbb-4990-be1f-87f522cb892e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>810283a3-9582-449a-92de-c4e36d408173</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>823e4c7a-f60f-4959-b70d-e59ec35c2ef2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a82297f-b6c1-44db-b1db-403c4f25e7b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/test admin role login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87e7e4bf-5246-4edc-b5f4-f41d6d634dbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d57e1c2a-d729-423a-a9dd-1d09c46d0249</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5104b13f-0a6a-4529-98e5-7eae4985a5a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/test username and password incorrectness</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d78af6f2-7463-4efe-9571-758a0182f002</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0750de5d-4701-46ab-ad46-2ba067c9d293</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
